package com.example.entity;
// Generated Jul 3, 2017 4:20:51 PM by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * UserJobsDetails generated by hbm2java
 */
@Entity
@Table(name = "JOB_DETAILS")
public class JobDetails implements java.io.Serializable {

	private BigDecimal id;
	private Job job;
	private String jobName;
	private String jobDesc;
	private Date jobDateTime;
	private Date createdDate;
	private Date modifiedDate;
	private String jobGrpName;

	public JobDetails() {
	}

	public JobDetails(Job job, String jobName, String jobDesc, Date jobDateTime) {
		this.job = job;
		this.jobName = jobName;
		this.jobDesc = jobDesc;
		this.jobDateTime = jobDateTime;
	}

	public JobDetails(Job job, String jobName, String jobDesc, Date jobDateTime, Date createdDate, Date modifiedDate,
			String jobGrpName) {
		this.job = job;
		this.jobName = jobName;
		this.jobDesc = jobDesc;
		this.jobDateTime = jobDateTime;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.jobGrpName = jobGrpName;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_GEN")
	@SequenceGenerator(name = "SEQ_GEN", sequenceName = "JOB_SEQ")
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_ID", nullable = false)
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@Column(name = "JOB_NAME", nullable = false, length = 100)
	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	@Column(name = "JOB_DESC", nullable = false, length = 1000)
	public String getJobDesc() {
		return this.jobDesc;
	}

	public void setJobDesc(String jobDesc) {
		this.jobDesc = jobDesc;
	}

	@Column(name = "JOB_DATE_TIME", nullable = false, length = 7)
	public Date getJobDateTime() {
		return this.jobDateTime;
	}

	public void setJobDateTime(Date jobDateTime) {
		this.jobDateTime = jobDateTime;
	}

	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "JOB_GRP_NAME", length = 100)
	public String getJobGrpName() {
		return this.jobGrpName;
	}

	public void setJobGrpName(String jobGrpName) {
		this.jobGrpName = jobGrpName;
	}

}
