package com.example.entity;
// Generated Jul 3, 2017 4:20:51 PM by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserJobsDetails generated by hbm2java
 */
@Entity
@Table(name = "USER_JOBS_DETAILS")
public class UserJobsDetails implements java.io.Serializable {

	private BigDecimal id;
	private UserJobs userJobs;
	private String jobName;
	private String jobDesc;
	private Date jobDateTime;
	private Date createdDate;
	private Date modifiedDate;
	private String jobGrpName;

	public UserJobsDetails() {
	}

	public UserJobsDetails(UserJobs userJobs, String jobName, String jobDesc, Date jobDateTime) {
		this.userJobs = userJobs;
		this.jobName = jobName;
		this.jobDesc = jobDesc;
		this.jobDateTime = jobDateTime;
	}

	public UserJobsDetails(UserJobs userJobs, String jobName, String jobDesc, Date jobDateTime, Date createdDate,
			Date modifiedDate, String jobGrpName) {
		this.userJobs = userJobs;
		this.jobName = jobName;
		this.jobDesc = jobDesc;
		this.jobDateTime = jobDateTime;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.jobGrpName = jobGrpName;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userJobs"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public UserJobs getUserJobs() {
		return this.userJobs;
	}

	public void setUserJobs(UserJobs userJobs) {
		this.userJobs = userJobs;
	}

	@Column(name = "JOB_NAME", nullable = false, length = 100)
	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	@Column(name = "JOB_DESC", nullable = false, length = 1000)
	public String getJobDesc() {
		return this.jobDesc;
	}

	public void setJobDesc(String jobDesc) {
		this.jobDesc = jobDesc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "JOB_DATE_TIME", nullable = false, length = 7)
	public Date getJobDateTime() {
		return this.jobDateTime;
	}

	public void setJobDateTime(Date jobDateTime) {
		this.jobDateTime = jobDateTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "JOB_GRP_NAME", length = 100)
	public String getJobGrpName() {
		return this.jobGrpName;
	}

	public void setJobGrpName(String jobGrpName) {
		this.jobGrpName = jobGrpName;
	}

}
